package com.vlab.backend.domain;

import static com.vlab.backend.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AbastecimentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbastecimentoAllPropertiesEquals(Abastecimento expected, Abastecimento actual) {
        assertAbastecimentoAutoGeneratedPropertiesEquals(expected, actual);
        assertAbastecimentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbastecimentoAllUpdatablePropertiesEquals(Abastecimento expected, Abastecimento actual) {
        assertAbastecimentoUpdatableFieldsEquals(expected, actual);
        assertAbastecimentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbastecimentoAutoGeneratedPropertiesEquals(Abastecimento expected, Abastecimento actual) {
        assertThat(actual)
            .as("Verify Abastecimento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbastecimentoUpdatableFieldsEquals(Abastecimento expected, Abastecimento actual) {
        assertThat(actual)
            .as("Verify Abastecimento relevant properties")
            .satisfies(a -> assertThat(a.getIdPosto()).as("check idPosto").isEqualTo(expected.getIdPosto()))
            .satisfies(a -> assertThat(a.getDataHora()).as("check dataHora").isEqualTo(expected.getDataHora()))
            .satisfies(a -> assertThat(a.getTipoCombustivel()).as("check tipoCombustivel").isEqualTo(expected.getTipoCombustivel()))
            .satisfies(a ->
                assertThat(a.getPrecoPorLitro())
                    .as("check precoPorLitro")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecoPorLitro())
            )
            .satisfies(a ->
                assertThat(a.getVolumeAbastecido())
                    .as("check volumeAbastecido")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getVolumeAbastecido())
            )
            .satisfies(a -> assertThat(a.getCpfMotorista()).as("check cpfMotorista").isEqualTo(expected.getCpfMotorista()))
            .satisfies(a -> assertThat(a.getImproperData()).as("check improperData").isEqualTo(expected.getImproperData()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbastecimentoUpdatableRelationshipsEquals(Abastecimento expected, Abastecimento actual) {
        // empty method
    }
}
